task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# D-FINE custom datasets use contiguous class IDs; for BDD100K these are 0-9.
num_classes: 10
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # The 'file_name' in the JSON already includes images/train/..., so the dataset root must point to bdd100k_final.
    img_folder: /root/rivermind-data/autodrive/datasets/datasets/bdd100k_final
    ann_file: /root/rivermind-data/autodrive/datasets/datasets/bdd100k_final/coco/annotations/instances_train_contiguous.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/rivermind-data/autodrive/datasets/datasets/bdd100k_final
    ann_file: /root/rivermind-data/autodrive/datasets/datasets/bdd100k_final/coco/annotations/instances_val_contiguous.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
